services:
  # Ubuntu Runner
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: ubuntu_image
    container_name: ubuntu_container
    volumes:
      - ./ubuntu_ar:/actions-runner
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    networks:
      - monitoring

  # Debian Runner
  debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
    image: debian_image
    container_name: debian_container
    volumes:
      - ./debian_ar:/actions-runner
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    networks:
      - monitoring

  # Arch Runner
  arch:
    build:
      context: .
      dockerfile: Dockerfile.arch
    image: arch_image
    container_name: arch_container
    volumes:
      - ./arch_ar:/actions-runner
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    networks:
      - monitoring

  # cAdvisor (Monitors container metrics)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  # Node Exporter (Monitors system metrics)
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring

  # Prometheus (Collects metrics)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  # Grafana (Visualizes metrics)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  grafana-storage:
