services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: ubuntu_image
    container_name: ubuntu_container
    volumes:
      - ./ubuntu_ar:/actions-runner
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
    image: debian_image
    container_name: debian_container
    volumes:
      - ./debian_ar:/actions-runner
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  arch:
    build:
      context: .
      dockerfile: Dockerfile.arch
    image: arch_image
    container_name: arch_container
    volumes:
      - ./arch_ar:/actions-runner
    stdin_open: true
    tty: true
    command: tail -f /dev/null
